:guid: %guid%
:user: devops
:numbered:
:lab_name: Convert To RHEL

= {lab_name}


== Overview
In this workshop you will convert a Centos 7 system into a Red Hat Enterprise Linux 7 system.

== Presentation of Materials

You are viewing a landing page called the *Dashboard*. The dashboard has the instructions and a terminal side by side.

This demo is designed to show the customer a separate terminal window with the presenter working from the dashboard.

NOTE: The dashboard terminal and the projected terminal are mirrored. Whatever you type in the dashboard terminal will be replicated on the terminal window shared with customers.

Deploy mirrored terminal window:

. Click the three horizontal bars at the upper right-hand corner of the dashboard and select *Open Terminal* 

. Click and drag the browser tab to separate the window if needed

=== Lab Access
. You can access your lab environment as *{user}* with password *%ssh_password%* with the following command.
+
[source,bash,role=execute]
----
%ssh_command%
----

. Switch to root user.
+
[source,bash,role=execute]
----
sudo su -
----

== Enabling the Convert2RHEL repository
The Convert2RHEL RPM is an offical Red Hat package. Therefore it is readily availble from the Red Hat software repository (CDN). As your CentOS server is not subscribed to the Red Hat CDN, you will need to enable the Convert2RHEL repository.

. You need to pull down the GPG signing key.
+
[source,bash,role=execute]
----
curl -o /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release https://www.redhat.com/security/data/fd431d51.txt
----

. Download the SSL certificate.
+
[source,bash,role=execute]
----
curl --create-dirs -o /etc/rhsm/ca/redhat-uep.pem https://ftp.redhat.com/redhat/convert2rhel/redhat-uep.pem
----

. Download the convert2rhel repository file.
+
[source,bash,role=execute]
----
curl -o /etc/yum.repos.d/convert2rhel.repo https://ftp.redhat.com/redhat/convert2rhel/7/convert2rhel.repo
----


== Installing the Convert2RHEL utility
 
Now that the requisite repository is enabled on your CentOS Linux system, it is time to install the Convert2RHEL utility and prepare the system for conversion.

. Before you begin the installation process, verify that you are running CentOS Linux and on the latest minor version.
+
[source,bash,role=execute]
----
cat /etc/centos-release
----

. Verify that the Convert2RHEL repo is enabled.
+
[source,bash,role=execute]
----
yum repolist
----

. Install the convert2rhel utility.
+
[source,bash,role=execute]
----
yum install -y convert2rhel
----


== Running the Convert2RHEL utility

. In order to automate this process, you need to use activation key in  the conversion command.
+
[source,bash,role=execute]
----
convert2rhel --org 12451665 --activationkey convert2rhel -y
----

+
NOTE: This process takes some time! The above process ask to confirm at several steps. Adding a `-y` as an argument will automate the input. Durging conversion the system will reboot for few times.


. Now that the conversion has been staged successfully, you will need to reboot the system in order to put the changes into effect.
+
[source,bash,role=execute]
----
reboot
----

. Verify the system is running on Red Hat Enterprise Linux.
+
[source,bash,role=execute]
----
cat /etc/redhat-release
----

. Verify that the necessary Red Hat repositories are enabled. Also, note that none of the old CentOS repos are available.
+
[source,bash,role=execute]
----
yum repolist
----

. Now you can review the logs from the conversion itself.
+
[source,bash,role=execute]
----
less /var/log/convert2rhel/convert2rhel.log
----
